# === CONFIGURACIÓN ===
TICKERS = [
    "GLEN_CFD.UK", "DTE_CFD.DE", "ORA_CFD.FR", "TEF_CFD.ES", "VOD_CFD.UK",
    "BMW_CFD.DE", "MBG_CFD.DE", "RNO_CFD.FR", "VOW_CFD.DE", "ML_CFD.FR",
    "ADS_CFD.DE", "PUM_CFD.DE", "GAW_CFD.UK", "MC_CFD.FR", "BTRW_CFD.UK",
    "HEIA_CFD.NL", "KWS_CFD.DE", "TSCO_CFD.UK", "OR_CFD.FR", "BATS_CFD.UK",
    "BP_CFD.UK", "CORN", "INDU_A_CFD.SE", "LGEN_CFD.UK", "BAYN_CFD.DE",
    "BARC_CFD.UK", "BBVA_CFD.ES", "CBK_CFD.DE", "DANSKE_CFD.DK", "LLOY_CFD.UK",
    "NDA_CFD.DK", "SEBa_CFD.SE", "PHIA_CFD.NL", "AIR_CFD.DE", "RR_CFD.UK",
    "AF_CFD.FR", "BBY_CFD.UK", "MAERSKa_CFD.DK", "COL_CFD.ES", "NOKIA_CFD.FI",
    "SAP_CFD.DE", "IBE_CFD.ES", "XAGUSD", "XAUUSD.sml", "AUDCAD", "AUDCHF",
    "AUDJPY", "AUDNZD", "AUDUSD.sml", "CADCHF", "CADJPY", "CHFJPY", "EURAUD",
    "EURCAD", "EURCHF", "EURCZK", "EURDKK", "EURGBP.sml", "EURHUF", "EURJPY",
    "EURNOK", "EURNZD", "EURPLN", "EURTRY", "EURUSD.sml", "GBPAUD", "GBPCAD",
    "GBPCHF", "GBPJPY.sml", "GBPNZD", "GBPUSD.sml", "NZDCAD", "NZDCHF", "NZDJPY",
    "NZDUSD", "SGDJPY", "TRYJPY", "USDCAD", "USDCHF", "USDCNH", "USDCZK",
    "USDDKK", "USDHKD", "USDHUF", "USDJPY.sml", "USDMXN", "USDNOK", "USDPLN",
    "USDSEK", "USDSGD", "USDTRY", "USDZAR", "ZARJPY", "ADAUSD", "AVAXUSD",
    "BCHUSD", "BNBUSD", "BTCUSD", "DOGEUSD", "DOTUSD", "EOSUSD", "ETHUSD",
    "GLMRUSD", "KSMUSD", "LINKUSD", "LTCUSD", "MATICUSD", "SOLUSD", "XLMUSD",
    "XTZUSD", "AU200", "CH20", "CHINAH", "CN50", "DE40", "ES35", "EU50", "FR40",
    "HK50", "JP225", "NL25", "SG30", "UK100", "US100", "US2000",
    "US30", "US500", "COPPER", "NATGAS", "SOYBN", "SUGAR", "UKOIL.sml",
    "USOIL.sml", "WHEAT", "AAPL_CFD.US", "AMZN_CFD.US", "BABA_CFD.US",
    "DIS_CFD.US", "F_CFD.US", "GE_CFD.US", "GOOGL_CFD.US", "META_CFD.US"
]
N_CANDLES = 1000
LOT = 0.1